# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'objDetection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for objDetection
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  target 'objDetectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'objDetectionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
